trigger:
- master

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    CBLOSC2_CACHE_FOLDER: $(Pipeline.Workspace)/.cblosc2

  steps:
    - task: CacheBeta@0
      inputs:
        key: cblosc2 | $(Agent.OS)
        path: ${CBLOSC2_CACHE_FOLDER}
      displayName: 'Cache c-blosc2'

    - bash: |
        git clone https://github.com/Blosc/c-blosc2.git
        pwd
        cd c-blosc2/
        mkdir build
        cd build/
        cmake ..
        cmake --build .
      displayName: 'Install dependencies'
      
    - bash: |
        ls -l ${BLOSC_INCLUDE}
        mkdir build
        cd build/
        ls -l ${BLOSC_DIR}
        cmake -DBLOSC_DIR=${BLOSC_DIR} -DBLOSC_INCLUDE=${BLOSC_INCLUDE} ..
        cmake --build .
      displayName: 'Build caterva'

    - bash: |
        cd build/tests/
        ls -l
        ./caterva_tests
      displayName: 'Tests'
