trigger:
- master

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - task: CacheBeta@0
        inputs:
          key: cblosc2 | $(Agent.OS) | cblosc2.lock
          path: .cache/c-blosc2/
        displayName: 'Cache c-blosc2'

    - bash: |
        git clone https://github.com/Blosc/c-blosc2.git
        cd c-blosc2/
        mkdir build
        cd build/
        cmake ..
        cmake --build .
      displayName: 'Install dependencies'
      
    - bash: |
        mkdir build
        cd build/
        cmake -DBLOSC_LIB=${BLOSC_LIB} -DBLOSC_INCLUDE=${BLOSC_INCLUDE} ..
        cmake --build .
      displayName: 'Build caterva'

    - bash: |
        cd build/tests/
        .cateva_tests
      displayName: 'Tests'
