trigger:
- master

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - bash: |
        git clone https://github.com/Blosc/c-blosc2.git
        cd c-blosc2/
        mkdir build
        cd build/
        cmake ..
        cmake --build .
      displayName: 'Install dependencies'
      
    - bash: |
        mkdir build
        cd build/
        cmake -DBLOSC_LIB=$BLOSC_LIB ..
        cmake --build .
      displayName: 'Build caterva'

    - bash: |
        cd build/tests/
        .cateva_tests
      displayName: 'Tests'
